### ISSUE TITLE
[HU4] Administrar póliza de un asegurado

### ISSUE THREAD

**Issue by Carlosma7** [Carlosma7/MedAuth#35]
**Como** administrativo **quiero** administrar la póliza de un asegurado **para** crear, modificar o dar de baja una póliza.

**Escenario**: Administrar póliza
* Dado: que un cliente tiene un usuario,
* Cuando: necesite administrar alguna información de la póliza,
* Entonces: la información asociada a la póliza del cliente queda registrada o eliminada.

**CoS**:
* Si el administrativo quiere crear una póliza:
    * El administrativo logra crear una póliza asociada a un cliente que no posea una previa activa.
    * El administrativo es informado ante errores en el procedimiento.
* Si el administrativo quiere modificar una póliza:
    * El administrativo logra modificar la información deseada sin modificar ninguna información ajena a la deseada.
    * El administrativo es informado ante errores en el procedimiento.
* Si el administrativo quiere desactivar una póliza:
    * El administrativo logra desactivar la póliza y queda registrada como inactiva.
    * El administrativo es informado ante errores en el procedimiento.

**Notas Funcionales**:

* Si el administrativo quiere crear una póliza:
    * No se puede tener una póliza activa antes de la creación de otra nueva.
    * Se debe comprobar que el tipo de póliza sea: _Básica_, _Total_ o _Extra_.
    * Se debe comprobar que los módulos extra, si los hay, sean: _Dental_, _Incapacidad_, _Desempleo_ o _Estética_.
* Si el administrativo quiere modificar una póliza:
    * Únicamente se pueden modificar la información que puede variar de un usuario: _Periodo de carencia_, _tipo de póliza_, _copagos_, _mensualidad_, _servicios excluidos_ y _modulos extra_.
    * Se debe comprobar que el tipo de póliza sea: _Básica_, _Total_ o _Extra_.
    * Se debe comprobar que los módulos extra, si los hay, sean: _Dental_, _Incapacidad_, _Desempleo_ o _Estética_.
* Si el administrativo quiere desactivar una póliza:
    * Una póliza no puede ser eliminada, solo desactivada.

**Notas Técnicas**:
* Si el administrativo quiere crear una póliza:
    * Se debe comprobar la existencia de usuarios existentes en el sistema con el identificador _DNI_, provocando una excepción que notifique al administrativo en caso contrario.
    * Se debe comprobar que, en caso de tener una póliza previa, esta esté desactivada, observando el flag _activa_.
    * Se debe comprobar que el tipo de póliza pertenece a un _enum_ definido de _tipoPoliza_, provocando una excepción que notifique al administrativo en caso contrario.
    * Se debe comprobar que los módulos extra, si los hay, pertenecen a un _enum_ definido de _moduloExtra_, provocando una excepción que notifique al administrativo en caso contrario.
* Si el administrativo quiere modificar una póliza:
    * Se debe comprobar la existencia de pólizas existentes en el sistema con el _identificador de póliza_, provocando una excepción que notifique al administrativo en caso contrario.
    * Se debe comprobar que el tipo de póliza pertenece a un _enum_ definido de _tipoPoliza_, provocando una excepción que notifique al administrativo en caso contrario.
    * Se debe comprobar que los módulos extra, si los hay, pertenecen a un _enum_ definido de _moduloExtra_, provocando una excepción que notifique al administrativo en caso contrario.
* Si el administrativo quiere desactivar una póliza:
    * Se debe comprobar la existencia de usuarios existentes en el sistema con el identificador _DNI_, provocando una excepción que notifique al administrativo en caso contrario.
    * Se debe comprobar que esta esté desactivada, observando el flag _activa_.

Se define la póliza por los siguientes atributos:

* usuario: UsuarioCliente
* id_poliza: str
* periodo_carencia: datetime
* tipo: TipoPoliza
* copagos: float
* mensualidad: str
* servicios_excluidos: List[str]
* modulos_extra: List[ModuloExtra]
* activa: bool

**Dependencias**:

* #43 [HU1] Crear usuario administrativo
* #44 [HU2] Crear usuario asegurado

**Tareas**:
* Crear modelo de póliza.
* Crear la lógica de creación de una póliza.
* Crear la lógica de modificación de una póliza.
* Crear la lógica de eliminación de una póliza.
* Diseñar las excepciones asociadas.

**Comment by arturocs** [comment]
¿Como se informa al administrativo del error?

**Comment by Carlosma7** [comment]
Mediante excepciones del sistema, aunque quizás debería especificarse más, lo tendré en cuenta de cara al diseño de la API, ya que este comportamiento evidentemente cambiará. ¡Gracias por el apunte!
