### ISSUE TITLE
[HU1] Crear usuario administrativo

### ISSUE THREAD

**Issue by Carlosma7** [Carlosma7/MedAuth#43]
**Como** usuario anónimo **quiero** crear un usuario administrativo en el sistema **para** gestionar el sistema.

**Escenario**:
* Dado: que un administrativo no tiene cuenta en el sistema,
* Cuando: solicite crear una cuenta,
* Entonces: la cuenta queda creada en el sistema.

**CoS**:
* El usuario anónimo obtiene un nuevo usuario administrativo en el sistema con una información válida.
* El usuario administrativo creado posee un email válido de empresa con el mismo nick que su email personal.
* El usuario anónimo es informado ante errores en el procedimiento.
* Se notifica al usuario anónimo si existe un usuario administrativo previamente creado con la misma información identificativa.

**Notas funcionales**:
* No se debe permitir que una persona tenga dos usuarios diferentes.
* Solo se deben permitir _DNIs_ válidos con el formato español.
* Solo se deben permitir correos válidos con dominio _.es_ o _.com_, y el correo empresarial debe utilizar el mismo usuario que el personal para la comodidad del empleado.

**Notas técnicas**:
* Se debe comprobar la existencia de usuarios existentes en el sistema con el mismo identificador _DNI_ para evitar la creación de uno nuevo, provocando una excepción que notifique al usuario.
* Se debe comprobar que el _DNI_ proporcionado sigue el formato ```123456789-A``` mediante una expresión regular, provocando una excepción si no cumple dicho formato.
* Se debe comprobar que el _email_ proporcionado sigue un formato sencillo, y que pertenece a un dominio del tipo _.es_ o _.com_ mediante una expresión regular, provocando una excepción si no cumple dicho formato.
* Se debe extraer el usuario del _email_ proporcionado para conformar el _email empresarial_ con el dominio propio de la empresa.

Se define el usuario por los siguientes atributos:

* nombre: str
* email: str
* id: str
* tipo: int

Se define además el usuario administrativo por los siguientes atributos añadidos:
* email_empresarial: str

**Dependencias**
* #44 [HU2] Crear usuario asegurado

**Tareas**
* Crear modelo de usuario genérico.
* Crear modelo de usuario administrativo.
* Crear la lógica de creación de un usuario administrativo.

**Comment by arturocs** [comment]
La restricción de que el usuario debe pertenecer a la empresa está implícita en la ultima nota técnica ¿No debería estar en las condiciones de satisfacción?

**Comment by Carlosma7** [comment]
Buenas Arturo, acabo de añadirlo. ¡Muchas gracias!
