### ISSUE TITLE
[HU2] Crear usuario asegurado

### ISSUE THREAD

**Issue by Carlosma7** [Carlosma7/MedAuth#44]
**Como** administrativo **quiero** crear un usuario para un asegurado en el sistema **para** usar el sistema.

**Escenario**: Crear usuario asegurado
* Dado: que un asegurado no tiene cuenta en el sistema,
* Cuando: solicite crear una cuenta,
* Entonces: la cuenta queda creada en el sistema.

**CoS**:
* El usuario administrativo obtiene un nuevo usuario cliente en el sistema con una información válida.
* El usuario administrativo es informado ante errores en el procedimiento.
* Se notifica al usuario administrativo si existe un usuario cliente previamente creado con la misma información identificativa.

**Notas Funcionales**:
* No se debe permitir que una persona tenga dos usuarios diferentes.
* Solo se deben permitir _DNIs_ válidos con el formato español.
* Solo se deben permitir correos válidos con dominio _.es_ o _.com_

**Notas Técnicas**:

* Se debe comprobar la existencia de usuarios existentes en el sistema con el mismo identificador _DNI_ para evitar la creación de uno nuevo, provocando una excepción que notifique al usuario.
* Se debe comprobar que el _DNI_ proporcionado sigue el formato ```123456789-A``` mediante una expresión regular, provocando una excepción si no cumple dicho formato.
* Se debe comprobar que el _email_ proporcionado sigue un formato sencillo consistente en la expresión regular ```([a-zA-Z0-9]+@[a-zA-Z]+\.)(com|es)```, provocando una excepción si no cumple dicho formato.
* Se debe comprobar que el _IBAN_ siga el formato de 22 dígitos con *ES* al inicio mediante una expresión regular, provocando una excepción si no cumple dicho formato.

Se define el usuario por los siguientes atributos:

* nombre: str
* email: str
* id: str
* tipo: int

Se define además el usuario cliente por los siguientes atributos añadidos:
* cuenta_bancaria: str

**Dependencias**:

* #43 [HU1] Crear usuario administrativo

**Tareas**:

**Tareas**
* Crear modelo de usuario genérico.
* Crear modelo de usuario administrativo.
* Crear la lógica de creación de un usuario administrativo.

**Comment by arturocs** [comment]
En la tercera nota técnica se dice que el email debe tener un "formato sencillo" ¿Que es exactamente un formato sencillo?

**Comment by Carlosma7** [comment]
Buenas Arturo, ya está solucionado, espero que quede más claro ahora, el formato es ```([a-zA-Z0-9]+@[a-zA-Z]+\.)(com|es)```.
