### ISSUE TITLE
DRY: Don't repeat yourself

### ISSUE THREAD

**Issue by JJ** [Carlosma7/MedAuth#83]
Si hay repetición de código, tiene que haber un bucle. O bien simplemente ejecutar el marco de tests y que encuentre él sólo todos los tests que tiene que ejecutar.

https://github.com/Carlosma7/MedAuth/blob/7b59b131dfcfd69653899aec83fbb7e13c5acb2c/tasks.py#L16-L37

**Comment by Carlosma7** [comment]
Comprendo, voy a buscar la forma de mejorarlo. ¡Gracias!

**Comment by Carlosma7** [comment]
Sería interesante ver la forma de obtener los nombres de los ficheros dada una ruta relativa en _Python_ . Se podría hacer mediante un _ls_. Se investigará esta opción.

**Comment by JJ** [comment]
SEguro que hay un glob o dir que acceda a eso de forma independiente del SO.

**Comment by Carlosma7** [comment]
Investigaré en esa línea. ¡Gracias!

**Comment by Carlosma7** [comment]
Se ha corregido, pero se encuentra en otra rama, una vez se realice el merge se cerrará automáticamente el issue.

* Se ha solucionado el código repetido en la tarea **test**:
https://github.com/Carlosma7/MedAuth/blob/e3a791a79c8dc64e849eb5271f9db0bafadd1e6a/tasks.py#L9-L13

* Se ha resumido también la tarea **clean**:
https://github.com/Carlosma7/MedAuth/blob/e3a791a79c8dc64e849eb5271f9db0bafadd1e6a/tasks.py#L3-L7
