### ISSUE TITLE
Sólo se usa assertpy una vez

### ISSUE THREAD

**Issue by JJ** [Carlosma7/MedAuth#84]
Si dices que lo usas, debes usarlo siempre, no una sola vez. Sólo se usa en un fichero.

**Comment by Carlosma7** [comment]
Cierto, aprovecho el *issue* para mejorar los tests. Muchas gracias por el apunte.

**Comment by Carlosma7** [comment]
Se ha corregido, pero se encuentra en otra rama, una vez se realice el merge se cerrará automáticamente el issue.

* _testUsuario_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testUsuario.py#L16-L19
* _testUsuarioAdmin_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testUsuarioAdmin.py#L16-L19
* _testUsuarioCliente_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testUsuarioCliente.py#L16-L19
* _testPoliza_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testPoliza.py#L24-L27
* _testPrescripcion_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testPrescripcion.py#L23-L26
* _testAutorizacion_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testAutorizacion.py#L24-L27
* _testCita_:
https://github.com/Carlosma7/MedAuth/blob/262afc6a96021ba4d79d4ed65458f580755dda2d/src/test/testCita.py#L25-L28

Además se ha comprobado que los tests funcionan correctamente y cumplen exactamente la misma función que la versión previa de los mismos.
