### ISSUE TITLE
Problemas comunes en las HHUU y en el código

### ISSUE THREAD

**Issue by januszewskimar** [Carlosma7/MedAuth#87]
**Problemas:**
* El código se relaciona con las HHUU en vez de issues para desarrollar.
* No hay CoS. Solo se encuentra el escenario de uso en las HHUU.
* Las notas funcionales en las HHUU están vacías.
* Las excepciones son genéricas. Deberían ser clases específicas para cada tipo de excepción.

**Comentarios positivos:**
* El código está bien comentado.
* El código está bien estructurado.
* Los test están completos.

**Comment by Carlosma7** [comment]
¡Muchas gracias Marcin! Los tendré en cuenta, y gracias por los comentarios positivos.

**Comment by Carlosma7** [comment]
Tengo que evaluar si realmente debo hacer clases específicas de excepción, o plantear un modelo distinto de cara al diseño de los microservicios con su _API_ y sus _responses_. Para tratar dicho problema crearé un _issue_ específico.

**Comment by Carlosma7** [comment]
Se menciona en el punto ```El código se relaciona con las HHUU en vez de issues para desarrollar.``` y aunque lleva toda la razón, es una mejora que se tendrá en cuenta a partir del punto actual, ya que crear _issues_ y relacionar todos los commits correspondientemente a estas alturas del desarrollo puede llegar a ser una tarea contraproducente y peligrosa.

Aprovecho este _issue_ como compromiso de esta buena práctica en un futuro.

**Comment by Carlosma7** [comment]
Para poder tener unas _HUs_ consistentes, lógicas y fáciles de comprender, se propone el siguiente formato antes de adaptar las existentes en el proyecto:

---

**Como** usuario **quiero** actividad **para** objetivo.

**Escenario**:
* Dado:
* Cuando:
* Entonces:

**CoS**

**Notas funcionales**

**Notas técnicas**

**Dependencias**

**Tareas**

---

Como anotaciones extra, se indicará _N/A_ cuando no aplique un determinado apartado en la _HU_.

**Comment by Carlosma7** [comment]
Se han corregido todas las _HUs_, se pueden observar a continuación:
* [[HU1] Crear usuario administrativo](https://github.com/Carlosma7/MedAuth/issues/43)
* [[HU2] Crear usuario asegurado](https://github.com/Carlosma7/MedAuth/issues/44)
* [[HU3] Administrar usuario](https://github.com/Carlosma7/MedAuth/issues/55)
* [[HU5] Consultar póliza de un asegurado](https://github.com/Carlosma7/MedAuth/issues/34)
* [[HU6] Añadir prescripción médica](https://github.com/Carlosma7/MedAuth/issues/36)
* [[HU7] Solicitar una autorización médica](https://github.com/Carlosma7/MedAuth/issues/37)
* [[HU8] Administrar autorización médica](https://github.com/Carlosma7/MedAuth/issues/39)
* [[HU9] Consultar autorización médica](https://github.com/Carlosma7/MedAuth/issues/38)
* [[HU10] Aprobar/Denegar autorización médica](https://github.com/Carlosma7/MedAuth/issues/40)
* [[HU11] Administrar cita médica](https://github.com/Carlosma7/MedAuth/issues/49)
* [[HU12] Consultar una cita médica](https://github.com/Carlosma7/MedAuth/issues/41)
* [[HU13] Notificar cita médica](https://github.com/Carlosma7/MedAuth/issues/42)

**Comment by Carlosma7** [comment]
Durante la corrección de las _HUs_, se han contemplado los siguientes errores, se creará un _issue_ específico para resolverlos:
* En la función ```modificar_usuario``` no se gestiona ninguna excepción para el formato de la cuenta bancaria.
* En la función ```crear_poliza``` no se gestiona ninguna excepción para el caso en el que la última póliza del usuario esté activa.
* En la función ```subir_prescripcion``` no se gestiona ninguna excepción para el formato de la _especialidad_.

Se han tenido en cuenta todas las sugerencias y actuado en consecuencia, resolveré los problemas restantes en nuevos _issues_ específicos. Cierro este _issue_ de forma manual.

**Comment by Carlosma7** [comment]
Se debe cerrar mediante un commit.
