### ISSUE TITLE
Errores en las historias de usuario

### ISSUE THREAD

**Issue by arturocs** [Carlosma7/MedAuth#90]
Dado que este proyecto ya ha sido revisado por otro alumno, la mayoría de fallos habituales ya han sido corregidos. No obstante he encontrado algunos problemas en la formulación de ciertas partes de las historias de usuario:

* En varias historias de usuario se hace referencia a un "formato sencillo de email" sin especificar en que consiste. [Comentario relacionado](https://github.com/Carlosma7/MedAuth/issues/44#issuecomment-749028380)
* A la hora de crear un usuario administrativo, no queda claramente especificado que el usuario debe pertenecer a la empresa.[Comentario relacionado](https://github.com/Carlosma7/MedAuth/issues/43#issuecomment-749024756)
* No se especifica como el sistema devuelve errores. [Comentario relacionado](https://github.com/Carlosma7/MedAuth/issues/35#issuecomment-749033500)
* Las dependencias de las HUs no están suficientemente detalladas

Comentarios positivos:
* Historias de usuario extensas y detalladas.
* Usa tipado estático para prevenir errores.

**Comment by Carlosma7** [comment]
¡Muchas gracias Arturo! Los tendré en cuenta, y gracias por los comentarios positivos.

**Comment by Carlosma7** [comment]
Acabo de responder a todos los comentarios en las diferentes _HUs_, y resuelto de la mejor forma posible. Me dispongo a detallar los enlaces de las dependencias que según comentas no resultan suficientemente aclaratorios.

**Comment by Carlosma7** [comment]
Ya he comentado todas las dependencias indicando las historias de usuario a las que corresponden. Cierro por lo tanto de forma manual este _issue_.

**Comment by Carlosma7** [comment]
Se debe cerrar mediante un commit.
